/* Generated by re2c 1.3 on Tue Jan 26 14:57:51 2021 */
#line 1 "Lexer.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

#include "Token.h"
#include "Location.h"
#include "Lexer.h"


Lexer* CreateLexer(FILE* in)
{
  Lexer* lxr = (Lexer*)malloc(sizeof(Lexer));
  memset(lxr->buf, 0, LEXER_BUF_SZ + 1);
  lxr->yych     = 0;
  lxr->end      = lxr->cursor = lxr->token = lxr->marker = lxr->buf + LEXER_BUF_SZ;
  lxr->yyaccept = 0;
  lxr->state    = -1;
  if (in)
  {
    if (in == stdin)
      lxr->is_stdin = true;
    else
      lxr->is_stdin = false;

    lxr->yyin = in;
  }
  else
  {
    lxr->yyin     = stdin;
    lxr->is_stdin = true;
  }
}

void DestroyLexer(Lexer* lexer)
{
    // this is only safe because the
    // lexer is defined as holding a
    // static sized array, meaning no
    // dynamic-allocation occurs
    // within the lexer.
    free(lexer);
}

void yySetBuffer(Lexer* lexer, char* text, int len)
{
    if (len > LEXER_BUF_SZ)
        FatalError("cannot buffer input text", __FILE__, __LINE__);

    memset(lexer->buf, 0, LEXER_BUF_SZ);
    memcpy(lexer->buf, text, len);

    lexer->cursor = lexer->marker = lexer->mrkctx = lexer->token = lexer->buf;
    lexer->end = lexer->buf + len;
}

char* dupstr(char* str, int len)
{
    char* result = (char*)malloc(sizeof(char) * len + 1);
    result = strncpy(result, str, len);
    result[len-1] = '\0';
    return result;
}

char* yyText(Lexer* lexer)
{
    return dupstr(lexer->token, lexer->cursor - lexer->token);
}

Location* yyLloc(Lexer* lexer)
{
    return &(lexer->yylloc);
}

void updatelloc(Location* llocp, char* token, int len)
{
    llocp->first_line   = llocp->last_line;
    llocp->first_column = llocp->last_column;

    for (int i = 0; i < len; i++)
    {
        if (token[i] == '\n')
        {
            llocp->last_line++;
            llocp->last_column = 1;
        }
        else
            llocp->last_column++;
    }
}


#line 97 "Lexer.re"


#define YYPEEK() *lexer->cursor
#define YYSKIP() ++(lexer->cursor)
#define YYBACKUP() lexer->marker = lexer->cursor
#define YYRESTORE() lexer->cursor = lexer->marker
#define YYBACKUPCTX() lexer->mrkctx = lexer->cursor
#define YYRESTORECTX() lexer->cursor = lexer->mrkctx
#define YYLESSTHAN(n) (lexer->end - lexer->cursor) < n

int yyLex(Lexer* lexer)
{
    LOOP:
    lexer->token = lexer->cursor;
    
#line 112 "Lexer.c"
{
	char yych;
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy4;
	case '!':
	case '$':
	case '%':
	case '&':
	case '*':
	case '+':
	case '-':
	case '/':
	case ':':
	case '<':
	case '=':
	case '>':
	case '@':
	case '^':
	case '|':
	case '~':	goto yy6;
	case '(':	goto yy9;
	case ')':	goto yy11;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	case ';':	goto yy16;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy18;
	case '\\':	goto yy21;
	default:
		if (YYLESSTHAN (1)) {
			goto yyeof;
		}
		goto yy2;
	}
yy2:
	YYSKIP ();
yy3:
#line 116 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_ERR; }
#line 214 "Lexer.c"
yy4:
	YYSKIP ();
#line 118 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); goto LOOP; }
#line 219 "Lexer.c"
yy6:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '!':
	case '$':
	case '%':
	case '&':
	case '*':
	case '+':
	case '-':
	case '/':
	case ':':
	case '<':
	case '=':
	case '>':
	case '@':
	case '^':
	case '|':
	case '~':	goto yy6;
	default:
		if (YYLESSTHAN (1)) {
		}
		goto yy8;
	}
yy8:
#line 119 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_OPERATOR; }
#line 248 "Lexer.c"
yy9:
	YYSKIP ();
#line 134 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_LPAREN; }
#line 253 "Lexer.c"
yy11:
	YYSKIP ();
#line 135 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_RPAREN; }
#line 258 "Lexer.c"
yy13:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	default:
		if (YYLESSTHAN (1)) {
		}
		goto yy15;
	}
yy15:
#line 126 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_INTEGER; }
#line 281 "Lexer.c"
yy16:
	YYSKIP ();
#line 136 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_SEMICOLON; }
#line 286 "Lexer.c"
yy18:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy18;
	default:
		if (YYLESSTHAN (1)) {
		}
		goto yy20;
	}
yy20:
#line 120 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_IDENTIFIER; }
#line 362 "Lexer.c"
yy21:
	YYSKIP ();
#line 128 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_BSLASH; }
#line 367 "Lexer.c"
yyeof:
#line 117 "Lexer.re"
	{ updatelloc(&(lexer->yylloc), lexer->token, lexer->cursor - lexer->token); return T_END; }
#line 371 "Lexer.c"
}
#line 143 "Lexer.re"

}
